[package]
name = "pc1500-rom-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pc1500-rom-test"
path = "pc1500_rom_execution_test.rs"

[dependencies]
anyhow = "1"

[dependencies.ceres-core]
path = "ceres-core"
